### ISSUE TITLE
Package Doesn't Follow SEMVER

### ISSUE THREAD

**Issue by fishcharlie** [song940/node-dns#39]
Version 1.4.2 to 1.4.3 included breaking changes, but was designated as a patch version. See this commit from @DSorlov: https://github.com/song940/node-dns/commit/643718017c5abbb6f79b2128a3cc5ab75bf7e907. Many functions and things were renamed, which is considered a breaking change according to [SEMVER](https://semver.org).

@song940 Why was the version number not bumped to 2.0.0 after this commit?

**Comment by song940** [comment]
@fishcharlie sorry about that, I'll fix version to 1.5.0 to make it right.

**Comment by fishcharlie** [comment]
@song940 Breaking changes should only be included in major versions. Bumping to 1.5.0 won't solve this issue. It should be bumped to 2.0.0. Not sure if you can also remove versions from NPM but that would need to be done as well to resolve this.

**Comment by fishcharlie** [comment]
@song940 Is this going to be resolved? This issue should not have been closed.

**Comment by pimterry** [comment]
@song940 this breaks all code that was using dns2 before v1.4.3, for everybody using this module. My test suite has just been broken by this change.

It seems like you're not clear why this is a problem, so just to explain:

* Semver uses a version number like 1.0.0 (Major.Minor.Patch versions). For a new version number, if only the patch version increased (1.0.0 -> 1.0.1) then it must be only a bugfix with everything still being compatible. If the minor version increased (1.0.0 -> 1.1.0) then some new features were added too, but it still _must_ be compatible with the previous versions. Only if the major increases (1.0.0 -> 2.0.0) is it allowed to be incompatible.
* Npm expects all modules to follow these rules. Because of that, by default when you install a dependency it is saved with a flexible version like `^1.0.0` (meaning 'I support any version >= 1.0.0 and <2.0.0').
* That's really useful, because it means if you release a new bugfix (v1.0.1) then other modules can upgrade and start using it automatically and know that nothing is going to break.
* Because you haven't changed the major version, other modules may upgrade to the new version of dns2 at any time. When they do, everything will break, because although the version says it's compatible, it's not (because many things were renamed).

Right now, all code that used dns2 before v1.4.3 has something like `"dns2": "^1.0.0"` in their package.json. At some point they will upgrade to the latest version that matches that (either when they update manually, when they run `npm update`, to resolve a version conflict, or _immediately_ if they don't use lockfiles or if that module is added as a dependency elsewhere) and that version will be today's v1.5.0, which doesn't work with their code from v1.4.2. When that happens, their whole system will unexpected break (like mine just did).

Could you please fix this? The current version should be changed to 2.0.0, and a fixed v1 version needs to be released to replace the current broken release (or v1.4.3/v1.5.0 need to be [unpublished](https://docs.npmjs.com/cli/v7/commands/npm-unpublish) from npm).

**Comment by fishcharlie** [comment]
It's disappointing that @song940 still has not addressed this. The latest commit was to add funding information (which was made after https://github.com/song940/node-dns/issues/39#issuecomment-810242776).

I'd happily consider donating to this project, but reliability is **critical**. It's hard to justify donating to a project that is so unstable.

**Comment by DSorlov** [comment]
@fishcharlie I see you have submitted fixes for the versioning errors. My screwup; did not realise the level of breaking changes and how that would impact. Lets see when @song940 have the time to commit them.

I am sure that @song940 will look at it as soon as he can. Most of us do this as a hobby and are perhaps not working with our projects here on git 24/7. I dont know about @song940 but he seems to update whenever he can.

**Comment by fishcharlie** [comment]
@DSorlov Sure, however I'm sure we can all agree that this is an extremely urgent and high priority issue.

As I mentioned, @song940 has committed to this repository since this comment: https://github.com/song940/node-dns/issues/39#issuecomment-810242776. I believe this raises legitimate questions about if @song940 realizes the severity of this issue. @song940 also has other GitHub activity even more recently.

If I was alerted to this issue, it would be **urgent** priority to fix and much more important than adding funding information to this project. Just by @song940's actions it seems like adding funding information is more important than this issue. Which I **STRONGLY** disagree with. This is a very urgent issue, it must be treated as such.

It's fine to be busy and have other priorities, but this issue is much higher priority than adding funding information to this project.

**Comment by song940** [comment]
Sorry guys, I’ll fix that as soon as possible.

**Comment by pimterry** [comment]
Thanks for fixing this @song940 :smiley:. I know being an open-source maintainer can be hard work sometimes, but I appreciate you sorting this out, and all your other hard work on this package!
