### ISSUE TITLE
use for DNS01 challenges?

### ISSUE THREAD

**Issue by btsimonh** [song940/node-dns#68]
Hi song940,

was searching around for a node based DNS server, and found this.
What I really want is some simple Node code which would respond with records for DNS01 AMCE challenges from LetsEncrypt.  

E.g. I found

https://github.com/krtab/agnos

but want to do it in node.

Has anyone suggested this use case to you?

br,

Simon

**Comment by stefanwerfling** [comment]
Hello Simon,

this is something else that is on the TODO list in my project [FlyingFish](https://github.com/stefanwerfling/flyingfish). I'm already doing a large part, but the "DNS01 AMCE challenges" itself is still missing. I would like to automatically store the DNS entries later when making the selection.

My DNS server can then be addressed by the NS record.

Or you imagine something special?

But Lets Encrypt does not belong to the [node-dns](https://github.com/song940/node-dns) project, so the implementation would be out of place here.

Because the DNS01 AMCE is just a record entry.

**Comment by andris9** [comment]
I have built a simple authoritative DNS server on top of node-dns that also supports DNS01 AMCE challenges - [PendingDNS](https://github.com/postalsys/pending-dns). The server uses [acme.js](https://www.npmjs.com/package/@root/acme) for Let's Encrypt integration and stores challenges in Redis.
